### ISSUE TITLE
Issue with create Shared Parameters / 2D DXF export.

### ISSUE THREAD

**Issue by GawrilowArtem** [jeremytammik/ExportCncFab#2] opened 2022-03-22 15:08 UTC
Hello Jeremy,

I faced an issue with creating Shared Parameters. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/102153320/159509775-928c9adb-5d7b-4435-9a5a-40d77a4669e8.png)

Currently, I'm using Revit 2020.2.8. 
A few weeks ago I already tested this plugin and it works without any issues. Please advice.

Also, I reached out to you some time ago about the possible export of 2D DXF/SAT files. For now, this function is not available.

![image](https://user-images.githubusercontent.com/102153320/159513464-d4b9a961-45f7-4379-8817-292c8b6eba63.png)

The Revit allows up to export 2D DXF, but for my purpose, it should be every element should be exported separately (the same as it works in your plugin in 3D). I trying to find an automation way to use the CNC machine with cladding plates in Revit (Revit(DXF) -> CAM -> CNC).

In addition, if it is possible to implement exporting of 2d elements as separate files - can these elements start from absolute zero coordinates (x=0,y=0,z=0)

Looking forward to hearing your thoughts
Thank you in advance.

**Comment by jeremytammik** [comment] 2022-03-22 16:05
Please note that this add-in is a programming sample. Intended audience is programmers implementing their own add-ins. Your issue sounds more like a feature request for new functionality. Sorry, that is completely out of scope.

**Comment by GawrilowArtem** [comment] 2022-03-22 21:42
Thank you for your response. 
Maybe you have any idea how to fix the issue with shared parameters?
I'm trying to find out how it works, but unfortunately for now it is super complicated for me. Sorry for a stupid question.

**Comment by jeremytammik** [comment] 2022-03-23 10:13
Yes, certainly. That is a very common error. It can mostly easily be solved by debugging the program and examining the object causing the null reference, cf. https://duckduckgo.com/?q=nullreferenceexception. Probably an object was not initialised as expected. Similar issues have been discussed many times in the Revit API discussion forum. I cannot reproduce it for you on my system, since I have a different setup than you. However, you can easily examine it on your s=ystem anbd then it will probably be easy to understand and solve.

**Closed as completed** 2022-03-23 10:16 UTC
